# Generated by Django 4.1 on 2022-09-01 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('web_lib', '0002_alter_book_options_book_author_alter_author_lit_type'), ('web_lib', '0003_alter_author_lit_type'), ('web_lib', '0004_alter_author_lit_type')]

    dependencies = [
        ('web_lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'get_latest_by': 'published', 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_lib.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='lit_type',
            field=models.CharField(choices=[('a', 'foreign'), ('b', 'domestic'), ('c', 'other')], default='a', max_length=1, verbose_name='Тип литературы'),
        ),
        migrations.AlterField(
            model_name='author',
            name='lit_type',
            field=models.CharField(choices=[('b', 'domestic'), ('c', 'other'), ('a', 'foreign')], default='a', max_length=1, verbose_name='Тип литературы'),
        ),
        migrations.AlterField(
            model_name='author',
            name='lit_type',
            field=models.CharField(choices=[('a', 'foreign'), ('b', 'domestic'), ('c', 'other')], default='a', max_length=1, verbose_name='Тип литературы'),
        ),
    ]
